<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books [
  <!ELEMENT books (book+)>
  <!ELEMENT book (title, author, price)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ATTLIST book
    id CDATA #REQUIRED
    year CDATA #IMPLIED>
]>
<books>
  <book id="1" year="2005">
    <title>Book One</title>
    <author>John Doe</author>
    <price>19.99</price>
  </book>
  <book id="2" year="2006">
    <title>Book Two</title>
    <author>Jane Doe</author>
    <price>15.99</price>
  </book>
</books>