<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personnel [
  <!ELEMENT personnel (name | address | phone)+>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ELEMENT phone (#PCDATA)>
  <!ATTLIST name
    id CDATA #REQUIRED
  >
  <!ATTLIST address
    street CDATA #IMPLIED
    city CDATA #IMPLIED
    state CDATA #IMPLIED
    zip CDATA #IMPLIED
  >
]>
<personnel>
 <name id="1">John Doe</name>
 <address>
  Street Number 123, <note>Flat number 4</note>
  City New York
  State NY
  Zip 10021
 </address>
 <phone> 1234567890</phone>
 <phone> 9876543210</phone>
</personnel>